service: tp
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  timeout: 30
  environment: ${file(configs.js)}
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline

custom:
  dotenvVars: ${file(configs.js)}
  webpack:
    includeModules: true

functions:
  hello:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /
          method: get
