name: Deploy to AWS [production]

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: .env
        run: cat>>.env<<EOF
          NODE_ENV=production
          EOF
          source .env

      - name: Install
        run: npm ci

      - name: Deploy Dev
        run: npx serverless deploy --stage prod
